version: '3.8'

services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: test_db
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: always
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network: